sheCode 2018 Update
ryanvade/shecode pull request #1
Opened 2018-10-18 16:23 UTC by Sech1

There may still be some small changes to the site, (FAQ, times, etc) but this has the working form and most other updates finished.

2018-10-19 15:01 UTC, ryanvade requested changes
Overall, I cannot accept. Please see the list of changes.

2018-10-19 15:01 UTC, ryanvade commented on config/mail.php
> +        'address' => env('MAIL_FROM_ADDRESS', 'no-reply@shecode.cs.siue.edu'),
I can't accept these changes in config/mail.php.  Referencing the Name and address for the mail settings should not be included with the repository, rather they need to be included in the installed configuration provided by the .env file. The .env file is already configured to provide these settings. See [Configuration - Laravel Docs](https://laravel.com/docs/5.5/configuration#environment-configuration)

2018-10-19 15:01 UTC, ryanvade commented on resources/views/join.blade.php
> +          <textarea id="allergies" class="input" rows="5" placeholder="List All Allergies" name="allergies" onchange="hideErrors()"></textarea>
PLease use this change for the textarea (info [HERE](https://bulma.io/documentation/form/textarea/))
```suggestion
          <textarea id="allergies" class="textarea" rows="5" placeholder="List All Allergies" name="allergies" onchange="hideErrors()"></textarea>
```

2018-10-19 15:01 UTC, ryanvade commented on config/mail.php
> +        'address' => env('MAIL_FROM_ADDRESS', 'no-reply@shecode.cs.siue.edu'),
I also cannot accept the PDFs. I understand the reason for including them but if this repo is used for another few years then more and more PDFs will be included.  This leads to repo junk. Please remove.

2018-10-23 01:11 UTC, ryanvade requested changes

2018-10-23 01:11 UTC, ryanvade commented on resources/views/index.blade.php
> +        Saturday Decemeber 1st, 2018<br>
```suggestion
        Saturday December 1st, 2018<br>
```

2018-10-23 01:53 UTC, Sech1 commented
Sorry I haven’t had time to make these changes yet this week, I have two tests (stat and programming languages) and work.
I will get to it when I can.

Jared Schooley

On Oct 22, 2018, at 8:11 PM, Ryan Owens <notifications@github.com<mailto:notifications@github.com>> wrote:


@ryanvade requested changes on this pull request.

________________________________

In resources/views/index.blade.php<https://github.com/ryanvade/shecode/pull/1#discussion_r227189067>:

> @@ -10,7 +10,7 @@
     <div class="container has-text-centered">
       <img src="/images/shecodeWhite.png" alt="SheCode" width="50%">
       <h2 class="subtitle">
-        Saturday Decemeber 2nd, 2017<br>
+        Saturday Decemeber 1st, 2018<br>


⬇️ Suggested change

-        Saturday Decemeber 1st, 2018<br>
+        Saturday December 1st, 2018<br>


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/ryanvade/shecode/pull/1#pullrequestreview-167171048>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AegxQ6HA-nxY7GST2NfHBl74B8xx8mWDks5unmzYgaJpZM4XtzSo>.

2018-10-23 05:16 UTC, Sech1 commented
Your requested changes should be added/complete

2018-10-23 14:35 UTC, merged