Dr.B's Requested Changes
ryanvade/shecode pull request #2
Opened 2018-10-23 18:29 UTC by Sech1

Please review these changes and let me know if anything else needs updated/modified.
These are the changes Dr.B wanted me to perform, and the additional data he wanted when the form was submitted.

If anything is incorrect or you have suggestions please let me know.

2018-10-23 18:34 UTC, Sech1 commented
I have also resolved any merge conflicts.

2018-10-23 19:26 UTC, Sech1 commented
Made some updates to fix crash if guardian values were left blank. 
This may change as Dr.B didn't specify if these should be allowed to be left blank or not.

2018-10-25 01:25 UTC, ryanvade requested changes
The allergies input needs to be fixed.  Requiring a textarea is bad.

2018-10-25 01:25 UTC, ryanvade commented on resources/views/join.blade.php
> +          <span class="icon is-small is-right">
I'm thinking we remove the `<span class="icon is-small is-right">
        <i class="fa fa-check"></i>
      </span>`

From both email fields.

2018-10-25 01:25 UTC, ryanvade commented on resources/views/join.blade.php
> +        <div class="control">
```suggestion
        <div class="control has-icons-left">
```

And then after the phone input:
`<span class="icon is-small is-lefft">
 	<i class="fa fa-phone" aria-hidden="true"></i>
 </span>`

2018-10-25 01:25 UTC, ryanvade commented on resources/views/join.blade.php
> +          <span class="icon is-small is-right">
Lets also change 
`<div class="column is-half-desktop has-text-centered">`
on line 8 to
`<div class="column is-two-thirds-desktop">`

As the increased amount of text and download links don't look terribly good centered with only half the screen.

2018-10-25 01:25 UTC, ryanvade commented on resources/views/join.blade.php
> +          <input id="name" class="input" type="text" placeholder="First Name" name="name" onchange="hideErrors()">
```suggestion
          <input id="name" class="input" type="text" placeholder="First Name" name="name" onchange="hideErrors()" required>
```
I forgot this as well on my version.

2018-10-25 01:25 UTC, ryanvade commented on resources/views/join.blade.php
> +          <input id="last" class="input" type="text" placeholder="Last Name" name="last" onchange="hideErrors()">
```suggestion
          <input id="last" class="input" type="text" placeholder="Last Name" name="last" onchange="hideErrors()" required>
```

2018-10-25 01:25 UTC, ryanvade commented on resources/views/join.blade.php
> +          <input id="last" class="input" type="text" placeholder="Last Name" name="last" onchange="hideErrors()">
Don't forget to add required to the student email input as well.

2018-10-25 01:25 UTC, ryanvade commented on app/Http/Controllers/SignupController.php
>            'allergies' => 'required',
So right now, it is impossible to submit the form without *something* in the text area. We should either not make it required setup some kind of notice on the client side. OR add a checkbox for 'My student doesn't have allergies'..something. So we can do a [required_unless](https://laravel.com/docs/5.5/validation#rule-required-unless) on the textarea with the checkbox.

2018-10-25 01:25 UTC, ryanvade commented on resources/views/join.blade.php
> +          <input id="last" class="input" type="text" placeholder="Last Name" name="last" onchange="hideErrors()">
And the shirts technically...my bad on these.

2018-10-25 01:25 UTC, ryanvade commented on app/Http/Controllers/SignupController.php
> +        if (!empty($request->input('guardianFirst'))) {
Lots of if/else statements.  A bit hard to read don't you think?

We can replace with:
`$guardianFirstVar = $request->input('guardianFirst') ?? 'No Parent or Guardian Entered';`

Uses the isset ternary/null coalesce operation available with PHP 7.

2018-10-25 01:25 UTC, ryanvade commented on app/Http/Controllers/SignupController.php
> +            $guardianLastVar = $request->input('guardianLast');
``$guardianLastVar = $request->input('guardianLast') ?? 'No Parent or Guardian Entered';``

2018-10-25 01:25 UTC, ryanvade commented on app/Http/Controllers/SignupController.php
> +            $guardianEmailVar = $request->input('guardianEmail');
`$guardianEmailVar = $request->input('guardianEmail') ?? 'No Parent or Guardian Email Entered';`

2018-10-25 01:25 UTC, ryanvade commented on app/Http/Controllers/SignupController.php
> +            $guardianNumberVar = $request->input('guardianNumber');
`$guardianNumberVar = $request->input('guardianNumber') ?? 'No Parent or Guardian Number Entered';`

2018-10-25 01:25 UTC, ryanvade commented on app/Http/Controllers/SignupController.php
>            'allergies' => 'required',
Technically, we should probably be validating the shirts with [required_in](https://laravel.com/docs/5.5/validation#rule-in)

But it is probably fine.

2018-10-25 01:26 UTC, ryanvade commented on resources/views/join.blade.php
> +          <span class="icon is-small is-right">
And also the `has-icons-right` class from those inputs.

2018-10-25 01:29 UTC, ryanvade commented
Apologies, for the late response. I can implement and resolve if you want (just say the word).  BUT I will need input on the allergies input.

2018-10-25 16:48 UTC, Sech1 commented
The requested changes have been made, I'll have to talk to Dr.B about how he wants to handle the allergies and students over the age of 18.
We may include a couple check boxes that hide the forms that aren't necessary if someone is over the age of 18 (Doesn't need a parent/guardian) or has no allergies. 

Let me know what you think about this going forward, I hopefully will be able to meet with Dr.B sometime this week.

2018-10-26 14:26 UTC, merged

2018-10-26 14:27 UTC, ryanvade commented
Those other changes need to be discussed before putting it live.